### ISSUE TITLE
Testowy issue dla Slacka

### ISSUE THREAD

**Issue by klasycznienielogiczny** [AGH-Narzedzia-Informatyczne/Kebattle.Live#19]
### Testowy issue

👀 

- [x] Sprawdzić jak to działa

- [x]  Ciekawe jak z Trello? 🤔 

- [x] Zamknąć testowy issue

**Comment by klasycznienielogiczny** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GitHub](https://trello.com/c/7GEdnViy/9-github)

**Comment by Azuyuto** [comment]
Wydaję mi się, że działa sztos

**Comment by klasycznienielogiczny** [comment]
Jest git. Zamykam 🔐
