### ISSUE TITLE
Funkcjonalność podglądu statystyk

### ISSUE THREAD

**Issue by pmalisz** [AGH-Narzedzia-Informatyczne/Kebattle.Live#25]
Należy dodać funkcjonalność w której dana firma będzie mogła przeglądnąć swoje statystyki odnośnie sprzedaży

**Comment by klasycznienielogiczny** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Stworzenie funkcjonalności podglądu statystyk (firma)](https://trello.com/c/4xKWEls6/16-stworzenie-funkcjonalno%C5%9Bci-podgl%C4%85du-statystyk-firma)
